# frozen_string_literal: true

source "https://rubygems.org"
#gemspec
#gem "jekyll"
#gem "kramdown-parser-gfm"
#gem "webrick"
gem 'github-pages', '~> 228'
gem "addressable"
gem "public_suffix"
gem "colorator"
gem "concurrent-ruby"
gem "em-websocket"
gem "eventmachine"
gem "http_parser.rb"
gem "ffi"
gem "forwardable-extended"
gem "i18n"
gem "jekyll"
gem "jekyll-sass-converter"
gem "jekyll-watch"
gem "kramdown"
gem "liquid"
gem "mercenary"
gem "pathutil"
gem "rouge"
gem "safe_yaml"
gem "jekyll-paginate-v2"
gem "sass"
gem "listen"
gem "rexml"
gem "kramdown-parser-gfm"
gem "rb-fsevent"
gem "rb-inotify"
gem "rake"
gem "sass-listen"
gem "webrick"
gem "faraday-retry"